define deb = Character("[deb_char_name]", color="#b96dff")
define jen = Character("[jen_char_name]", color="#ff6df0")
define eri = Character("Erik", color="#56aaff")
define rox = Character("Roxxy", color="#c8ffc8")
define mia = Character("Mia", color="#c499ff")
define mrsjo = Character("Mrs. Johnson", color="#c8ffc8")
define mon = Character("Monster Girl", color="#c8ffc8")
define dex = Character("Dexter", color="#c8ffc8")
define ron = Character("Ronda", color="#c8ffc8")
define bri = Character("Coach Bridget", color="#c8ffc8")
define smi = Character("Principal Smith", color="#c8ffc8")
define bis = Character("Miss Bissette", color="#c8ffc8")
define eve = Character("Eve", color="#c8ffc8")
define dia = Character("Diane", color="#c8ffc8")
define mas = Character("Master Somrak", color="#c8ffc8")
define ton = Character("Tony", color="#c8ffc8")
define cam = Character("Camilla", color="#c8ffc8")
define igo = Character("Igor", color="#c8ffc8")
define hen = Character("Henchman", color="#c8ffc8")
define lar = Character("Larry", color="#c8ffc8")
define sus = Character("Susan", color="#c8ffc8")
define gin = Character("Nurse Ginger", color="#c8ffc8")
define jud = Character("Judith", color="#c8ffc8")
define ann = Character("Annie", color="#c8ffc8")
define cas = Character("Cassie", color="#c8ffc8")
define jan = Character("Jane", color="#c8ffc8")
define kev = Character("Kevin", color="#c8ffc8")
define liu = Character("Banker", color="#c8ffc8")
define martinez = Character("Martinez", color="#c8ffc8")
define lopez = Character("Lopez", color="#c8ffc8")
define ross = Character("Miss Ross", color="#c8ffc8")
define dewitt = Character("Miss Dewitt", color="#c8ffc8")
define okita = Character("Miss Okita", color="#c8ffc8")
define june = Character("June", color="#a771b6")
define beth = Character("Beth", color="#ce6b6a")
define sara = Character("Sara")
define aqua = Character("Aqua")
define ced = Character("Cedric")
define chi = Character("Chico")
define helen = Character("Helen")
define harold = Character("Harold")
define ivy = Character("Ivy")
define vero = Character("Veronica")
define awesomo = Character("Dog")
define rump = Character("Mayor Rump")
define tony = Character("Tony")
define maria = Character("Maria")
define tonymaria = Character ("Tony and Maria")
define Mr.Sato = Character("Mr. Sato")
define Josephine = Character ("Josephine")
define henchman2 = Character ("Henchmen")
define chad = Character("Chad")
define tyrone = Character("Tyrone")
define Terry = Character("Terry")
define poker_sayer02 = Character("Bot")
define anna = Character("Anna")
define bub = Character("Mr. Bubbles")
define ang = Character("Sister Angelica")
define ear = Character("Earl")
define yum = Character("Yumi")
define tati = Character("Tatiana")
define iwanka = Character("Iwanka")
define becca = Character("Becca")
define missy = Character("Missy")
define micoe = Character("Micoe")
define thief = Character("Thief")
define larry = Character("Larry")
define crys = Character("Crystal")
define grace = Character("Grace")
define roz = Character("Roz")
define guard = Character("Guard")
define jaing = Character("Jiang")
define Kass = Character("Kass")
define clyde = Character("Clyde")
define pig = Character("dog")
define buyer = Character("Buyer")
define pilly = Character("Pilly")
define cat = Character("Cat", color="#c87efe")
define kont = Character("Konterina", color="#f093ff")
define PA = Character("PA", color="#86a5a3")
define Sploosh = Character("Sploosh")
define kim = Character("Kim")

define player_name = Character('[firstname]', color="#6f96f1")
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
