define deb = Character("[deb_char_name]", color="#b96dff")
define jen = Character("[jen_char_name]", color="#ff6df0")
define eri = Character("Эрик", color="#56aaff")
define rox = Character("Рокси", color="#c8ffc8")
define mia = Character("Мия", color="#c499ff")
define mrsjo = Character("Миссис Джонсон", color="#c8ffc8")
define mon = Character("Девушка-монстр", color="#c8ffc8")
define dex = Character("Декстер", color="#c8ffc8")
define ron = Character("Ронда", color="#c8ffc8")
define bri = Character("Тренер Бриджит", color="#c8ffc8")
define smi = Character("Директор Смит", color="#c8ffc8")
define bis = Character("Мисс Биссетт", color="#c8ffc8")
define eve = Character("Ева", color="#c8ffc8")
define dia = Character("Диана", color="#c8ffc8")
define mas = Character("Мастер Сомрак", color="#c8ffc8")
define ton = Character("Тони", color="#c8ffc8")
define cam = Character("Камилла", color="#c8ffc8")
define igo = Character("Игорь", color="#c8ffc8")
define hen = Character("Приспешник", color="#c8ffc8")
define lar = Character("Ларри", color="#c8ffc8")
define sus = Character("Сьюзан", color="#c8ffc8")
define gin = Character("Медсестра Джинджер", color="#c8ffc8")
define jud = Character("Джуди", color="#c8ffc8")
define ann = Character("Энни", color="#c8ffc8")
define cas = Character("Кэсси", color="#c8ffc8")
define jan = Character("Джейн", color="#c8ffc8")
define kev = Character("Кевин", color="#c8ffc8")
define liu = Character("Банкир", color="#c8ffc8")
define martinez = Character("Мартинез", color="#c8ffc8")
define lopez = Character("Лопес", color="#c8ffc8")
define ross = Character("Мисс Росс", color="#c8ffc8")
define dewitt = Character("Мисс Девитт", color="#c8ffc8")
define okita = Character("Мисс Окита", color="#c8ffc8")
define june = Character("Джун", color="#a771b6")
define beth = Character("Бесс", color="#ce6b6a")
define sara = Character("Сара")
define aqua = Character("Аква")
define ced = Character("Седрик")
define chi = Character("Чико")
define helen = Character("Хелен")
define harold = Character("Гарольд")
define ivy = Character("Айви")
define vero = Character("Вероника")
define awesomo = Character("Собака")
define rump = Character("Мэр Рамп")
define tony = Character("Тони")
define maria = Character("Мария")
define tonymaria = Character ("Тони и Мария")
define Mr.Sato = Character("Мр. Сато")
define Josephine = Character ("Жозефина")
define henchman2 = Character ("Пособники")
define chad = Character("Чад")
define tyrone = Character("Тайрон")
define Terry = Character("Терри")
define poker_sayer02 = Character("Бот")
define anna = Character("Анна")
define bub = Character("Мр. Пузырёв")
define ang = Character("Сестра Анжелика")
define ear = Character("Граф")
define yum = Character("Юми")
define tati = Character("Татьяна")
define iwanka = Character("Иванка")
define becca = Character("Бекка")
define missy = Character("Мисси")
define micoe = Character("Мико")
define thief = Character("Вор")
define larry = Character("Ларри")
define crys = Character("Кристалл")
define grace = Character("Грейс")
define roz = Character("Роза")
define guard = Character("Охранник")
define jaing = Character("Цзян")
define Kass = Character("Касс")
define clyde = Character("Клайд")
define pig = Character("собака")
define buyer = Character("Клиент")
define pilly = Character("Пилли")
define cat = Character("Кошка", color="#c87efe")
define kont = Character("Катрина", color="#f093ff")
define PA = Character("ПА", color="#86a5a3")
define Sploosh = Character("Сплуш")
define kim = Character("Ким")

define player_name = Character('[firstname]', color="#6f96f1")
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
