define chr_warn = "{color=#b61c1c}{b}[CHR]: {/b}{/color}"
define str_warn = "{color=#b61c1c}{b}[STR]: {/b}{/color}"
define dex_warn = "{color=#b61c1c}{b}[DEX]: {/b}{/color}"
define int_warn = "{color=#b61c1c}{b}[INT]: {/b}{/color}"
define chr_pass = "{color=#00ff00}{b}[CHR]: {/b}{/color}"
define str_pass = "{color=#00ff00}{b}[STR]: {/b}{/color}"
define dex_pass = "{color=#00ff00}{b}[DEX]: {/b}{/color}"
define int_pass = "{color=#00ff00}{b}[INT]: {/b}{/color}"
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
