image player 1f = im.Flip("characters/player/char_player_01.png", horizontal=True)
image player 2f = im.Flip("characters/player/char_player_02.png", horizontal=True)
image player 3f = im.Flip("characters/player/char_player_03.png", horizontal=True)
image player 4f = im.Flip("characters/player/char_player_04.png", horizontal=True)
image player 5f = im.Flip("characters/player/char_player_05.png", horizontal=True)
image player 6f = im.Flip("characters/player/char_player_06.png", horizontal=True)
image player 7f = im.Flip("characters/player/char_player_07.png", horizontal=True)
image player 8f = im.Flip("characters/player/char_player_08.png", horizontal=True)
image player 8bf = im.Flip("characters/player/char_player_08b.png", horizontal=True)
image player 9f = im.Flip("characters/player/char_player_09.png", horizontal=True)
image player 10f = im.Flip("characters/player/char_player_10.png", horizontal=True)
image player 11f = im.Flip("characters/player/char_player_11.png", horizontal=True)
image player 12f = im.Flip("characters/player/char_player_12.png", horizontal=True)
image player 13f = im.Flip("characters/player/char_player_13.png", horizontal=True)
image player 14f = im.Flip("characters/player/char_player_14.png", horizontal=True)
image player 15f = im.Flip("characters/player/char_player_15.png", horizontal=True)
image player 16f = im.Flip("characters/player/char_player_16.png", horizontal=True)
image player 17f = im.Flip("characters/player/char_player_17.png", horizontal=True)
image player 18f = im.Flip("characters/player/char_player_18.png", horizontal=True)
image player 19f = im.Flip("characters/player/char_player_19.png", horizontal=True)
image player 20f = im.Flip("characters/player/char_player_20.png", horizontal=True)
image player 21f = im.Flip("characters/player/char_player_21.png", horizontal=True)
image player 22f = im.Flip("characters/player/char_player_22.png", horizontal=True)
image player 23f = im.Flip("characters/player/char_player_23.png", horizontal=True)
image player 24f = im.Flip("characters/player/char_player_24.png", horizontal=True)
image player 25f = im.Flip("characters/player/char_player_25.png", horizontal=True)
image player 26f = im.Flip("characters/player/char_player_26.png", horizontal=True)
image player 27f = im.Flip("characters/player/char_player_27.png", horizontal=True)
image player 28f = im.Flip("characters/player/char_player_28.png", horizontal=True)
image player 29f = im.Flip("characters/player/char_player_29.png",xoffset=-8, horizontal=True)
image player 30f = im.Flip("characters/player/char_player_30.png", horizontal=True)
image player 31f = im.Flip("characters/player/char_player_31.png", horizontal=True)
image player 32f = im.Flip("characters/player/char_player_32.png", horizontal=True)
image player 33f = im.Flip("characters/player/char_player_33.png", horizontal=True)
image player 34f = im.Flip("characters/player/char_player_34.png", horizontal=True)
image player 35f = im.Flip("characters/player/char_player_35.png", horizontal=True)
image player 36f = im.Flip("characters/player/char_player_36.png", horizontal=True)
image player 37f = im.Flip("characters/player/char_player_37.png", horizontal=True)
image player 38f = im.Flip("characters/player/char_player_38.png", horizontal=True)
image player 39f = im.Flip("characters/player/char_player_39.png", horizontal=True)
image player 40f = im.Flip("characters/player/char_player_40.png", horizontal=True)
image player 41f = im.Flip("characters/player/char_player_41.png", horizontal=True)
image player 42f = im.Flip("characters/player/char_player_42.png", horizontal=True)
image player 43f = im.Flip("characters/player/char_player_43.png", horizontal=True)
image player 44f = im.Flip("characters/player/char_player_44.png", horizontal=True)
image player 45f = im.Flip("characters/player/char_player_45.png", horizontal=True)
image player 46f = im.Flip("characters/player/char_player_46.png", horizontal=True)
image player 47f = im.Flip("characters/player/char_player_47.png", horizontal=True)
image player 48f = im.Flip("characters/player/char_player_48.png", horizontal=True)
image player 49f = im.Flip("characters/player/char_player_49.png", horizontal=True)
image player 50f = im.Flip("characters/player/char_player_50.png", horizontal=True)
image player 51f = im.Flip("characters/player/char_player_51.png", horizontal=True)
image player 52f = im.Flip("characters/player/char_player_52.png", horizontal=True)
image player 53f = im.Flip("characters/player/char_player_53.png", horizontal=True)
image player 54f = im.Flip("characters/player/char_player_54.png", horizontal=True)
image player 55f = im.Flip("characters/player/char_player_55.png", horizontal=True)
image player 56f = im.Flip("characters/player/char_player_56.png", horizontal=True)
image player 57f = im.Flip("characters/player/char_player_57.png", horizontal=True)
image player 58f = im.Flip("characters/player/char_player_58.png", horizontal=True)
image player 59f = im.Flip("characters/player/char_player_59.png", horizontal=True)
image player 60f = im.Flip("characters/player/char_player_60.png", horizontal=True)
image player 61f = im.Flip("characters/player/char_player_61.png", horizontal=True)
image player 62f = im.Flip("characters/player/char_player_62.png", horizontal=True)
image player 63f = im.Flip("characters/player/char_player_63.png", horizontal=True)
image player 64f = im.Flip("characters/player/char_player_64.png", horizontal=True)
image player 65f = im.Flip("characters/player/char_player_65.png", horizontal=True)
image player 66f = im.Flip("characters/player/char_player_66.png", horizontal=True)
image player 67f = im.Flip("characters/player/char_player_67.png", horizontal=True)
image player 67bf = im.Flip("characters/player/char_player_67b.png", horizontal=True)
image player 67cf = im.Flip("characters/player/char_player_67c.png", horizontal=True)
image player 68f = im.Flip("characters/player/char_player_68.png", horizontal=True)
image player 68bf = im.Flip("characters/player/char_player_68b.png", horizontal=True)
image player 69f = im.Flip("characters/player/char_player_69.png", horizontal=True)
image player 70f = im.Flip("characters/player/char_player_70.png", horizontal=True)
image player 71f = im.Flip("characters/player/char_player_71.png", horizontal=True)
image player 72f = im.Flip("characters/player/char_player_72.png", horizontal=True)
image player 73f = im.Flip("characters/player/char_player_73.png", horizontal=True)
image player 74f = im.Flip("characters/player/char_player_74.png", horizontal=True)
image player 75f = im.Flip("characters/player/char_player_75.png", horizontal=True)
image player 76f = im.Flip("characters/player/char_player_76.png", horizontal=True)
image player 77f = im.Flip("characters/player/char_player_77.png", horizontal=True)
image player 78f = im.Flip("characters/player/char_player_78.png", horizontal=True)
image player 79f = im.Flip("characters/player/char_player_79.png", horizontal=True)
image player 80f = im.Flip("characters/player/char_player_80.png", horizontal=True)
image player 81f = im.Flip("characters/player/char_player_81.png", horizontal=True)
image player 82f = im.Flip("characters/player/char_player_82.png", horizontal=True)
image player 83f = im.Flip("characters/player/char_player_83.png", horizontal=True)
image player 83bf = im.Flip("characters/player/char_player_83b.png", horizontal=True)
image player 83cf = im.Flip("characters/player/char_player_83c.png", horizontal=True)
image player 84f = im.Flip("characters/player/char_player_84.png", horizontal=True)
image player 85f = im.Flip("characters/player/char_player_85.png", horizontal=True)
image player 86f = im.Flip("characters/player/char_player_86.png", horizontal=True)
image player 87f = im.Flip("characters/player/char_player_87.png", horizontal=True)
image player 88f = im.Flip("characters/player/char_player_88.png", horizontal=True)
image player 89f = im.Flip("characters/player/char_player_89.png", horizontal=True)
image player 90f = im.Flip("characters/player/char_player_90.png", horizontal=True)
image player 91f = im.Flip("characters/player/char_player_91.png", horizontal=True)
image player 92f = im.Flip("characters/player/char_player_92.png", horizontal=True)
image player 93f = im.Flip("characters/player/char_player_93.png", horizontal=True)
image player 94f = im.Flip("characters/player/char_player_94.png", horizontal=True)
image player 95f = im.Flip("characters/player/char_player_95.png", horizontal=True)
image player 96f = im.Flip("characters/player/char_player_96.png", horizontal=True)
image player 97f = im.Flip("characters/player/char_player_97.png", horizontal=True)

image player 99f = im.Flip("characters/player/char_player_99.png", horizontal=True)
image player 100f = im.Flip("characters/player/char_player_100.png", horizontal=True)
image player 100bf = im.Flip( "characters/player/char_player_100b.png", horizontal=True)
image player 101f = im.Flip("characters/player/char_player_101.png", horizontal=True)
image player 101bf = im.Flip( "characters/player/char_player_101b.png", horizontal=True)
image player 102f = im.Flip("characters/player/char_player_102.png", horizontal=True)
image player 103f = im.Flip("characters/player/char_player_103.png", horizontal=True)
image player 104f = im.Flip("characters/player/char_player_104.png", horizontal=True)
image player 105f = im.Flip("characters/player/char_player_105.png", horizontal=True)
image player 106f = im.Flip("characters/player/char_player_106.png", horizontal=True)
image player 107f = im.Flip("characters/player/char_player_107.png", horizontal=True)
image player 108f = im.Flip("characters/player/char_player_108.png", horizontal=True)
image player 109f = im.Flip("characters/player/char_player_109.png", horizontal=True)
image player 110f = im.Flip("characters/player/char_player_110.png", horizontal=True)
image player 111f = im.Flip("characters/player/char_player_111.png", horizontal=True)
image player 112f = im.Flip("characters/player/char_player_112.png", horizontal=True)
image player 113f = im.Flip("characters/player/char_player_113.png", horizontal=True)
image player 114f = im.Flip("characters/player/char_player_114.png", horizontal=True)
image player 115f = im.Flip("characters/player/char_player_115.png", horizontal=True)
image player 116f = im.Flip("characters/player/char_player_116.png", horizontal=True)
image player 117f = im.Flip("characters/player/char_player_117.png", horizontal=True)
image player 118f = im.Flip("characters/player/char_player_118.png", horizontal=True)
image player 119f = im.Flip("characters/player/char_player_119.png", horizontal=True)
image player 120f = im.Flip("characters/player/char_player_120.png", horizontal=True)
image player 121f = im.Flip("characters/player/char_player_121.png", horizontal=True)
image player 122f = im.Flip("characters/player/char_player_122.png", horizontal=True)
image player 123f = im.Flip("characters/player/char_player_123.png", horizontal=True)
image player 124f = im.Flip("characters/player/char_player_124.png", horizontal=True)
image player 125f = im.Flip("characters/player/char_player_125.png", horizontal=True)
image player 126f = im.Flip("characters/player/char_player_126.png", horizontal=True)
image player 127f = im.Flip("characters/player/char_player_127.png", horizontal=True)
image player 128f = im.Flip("characters/player/char_player_128.png", horizontal=True)
image player 129f = im.Flip("characters/player/char_player_129.png", horizontal=True)
image player 130f = im.Flip("characters/player/char_player_130.png", horizontal=True)
image player 131f = im.Flip("characters/player/char_player_131.png", horizontal=True)
image player 132f = im.Flip("characters/player/char_player_132.png", horizontal=True)
image player 133f = im.Flip("characters/player/char_player_133.png", horizontal=True)
image player 134f = im.Flip("characters/player/char_player_134.png", horizontal=True)
image player 135f = im.Flip("characters/player/char_player_135.png", horizontal=True)
image player 136f = im.Flip("characters/player/char_player_136.png", horizontal=True)
image player 137f = im.Flip("characters/player/char_player_137.png", horizontal=True)
image player 138f = im.Flip("characters/player/char_player_138.png", horizontal=True)
image player 139f = im.Flip("characters/player/char_player_139.png", horizontal=True)
image player 140f = im.Flip("characters/player/char_player_140.png", horizontal=True)
image player 141f = im.Flip("characters/player/char_player_141.png", horizontal=True)
image player 142f = im.Flip("characters/player/char_player_142.png", horizontal=True)
image player 143f = im.Flip("characters/player/char_player_143.png", horizontal=True)
image player 144f = im.Flip("characters/player/char_player_144.png", horizontal=True)
image player 145f = im.Flip("characters/player/char_player_145.png", horizontal=True)
image player 146f = im.Flip("characters/player/char_player_146.png", horizontal=True)
image player 147f = im.Flip("characters/player/char_player_147.png", horizontal=True)
image player 148f = im.Flip("characters/player/char_player_148.png", horizontal=True)
image player 149f = im.Flip("characters/player/char_player_149.png", horizontal=True)
image player 150f = im.Flip("characters/player/char_player_150.png", horizontal=True)
image player 151f = im.Flip("characters/player/char_player_151.png", horizontal=True)
image player 152f = im.Flip("characters/player/char_player_152.png", horizontal=True)
image player 153f = im.Flip("characters/player/char_player_153.png", horizontal=True)
image player 154f = im.Flip("characters/player/char_player_154.png", horizontal=True)
image player 155f = im.Flip("characters/player/char_player_155.png", horizontal=True)
image player 156f = im.Flip("characters/player/char_player_156.png", horizontal=True)
image player 157f = im.Flip("characters/player/char_player_157.png", horizontal=True)
image player 158f = im.Flip("characters/player/char_player_158.png", horizontal=True)
image player 159f = im.Flip("characters/player/char_player_159.png", horizontal=True)
image player 160f = im.Flip("characters/player/char_player_160.png", horizontal=True)
image player 161f = im.Flip("characters/player/char_player_161.png", horizontal=True)
image player 162f = im.Flip("characters/player/char_player_162.png", horizontal=True)
image player 163f = im.Flip("characters/player/char_player_163.png", horizontal=True)
image player 164f = im.Flip("characters/player/char_player_164.png", horizontal=True)
image player 165f = im.Flip("characters/player/char_player_165.png", horizontal=True)
image player 166f = im.Flip("characters/player/char_player_166.png", horizontal=True)
image player 167f = im.Flip("characters/player/char_player_167.png", horizontal=True)
image player 168f = im.Flip("characters/player/char_player_168.png", horizontal=True)
image player 174bf = im.Flip("characters/player/char_player_174b.png",xoffset=-38, horizontal=True)
image player 184f = im.Flip("characters/player/char_player_184.png", horizontal=True)
image player 184bf = im.Flip("characters/player/char_player_184b.png", horizontal=True)
image player 192f = im.Flip("characters/player/char_player_192.png", horizontal=True)
image player 203f = im.Flip("characters/player/char_player_203.png", horizontal=True)
image player 209f = im.Flip("characters/player/char_player_209.png", horizontal=True)
image player 210f = im.Flip("characters/player/char_player_210.png", horizontal=True)
image player 212f = im.Flip("characters/player/char_player_212.png", horizontal=True)
image player 239f = im.Flip("characters/player/char_player_239.png",xoffset=-5,horizontal=True)
image player 240f = im.Flip("characters/player/char_player_240.png",xoffset=-5,horizontal=True)
image player 261f = im.Flip("characters/player/char_player_261.png", horizontal=True)
image player 261bf = im.Flip("characters/player/char_player_261b.png", horizontal=True)
image player 262f = im.Flip("characters/player/char_player_262.png", horizontal=True)
image player 262bf = im.Flip("characters/player/char_player_262b.png", horizontal=True)
image player 263f = im.Flip("characters/player/char_player_263.png", horizontal=True)
image player 263bf = im.Flip("characters/player/char_player_263b.png", horizontal=True)
image player 263cf = im.Flip("characters/player/char_player_263c.png", horizontal=True)
image player 365f = im.Flip("characters/player/char_player_365.png", horizontal=True)
image player 366f = im.Flip("characters/player/char_player_366.png", horizontal=True)
image player 367f = im.Flip("characters/player/char_player_367.png", horizontal=True)
image player 368f = im.Flip("characters/player/char_player_368.png", horizontal=True)
image player 384f = im.Flip("characters/player/char_player_384.png", horizontal=True)
image player 385f = im.Flip("characters/player/char_player_385.png", horizontal=True)
image player 386f = im.Flip("characters/player/char_player_386.png", horizontal=True)
image player 401f = im.Flip("characters/player/char_player_401.png", horizontal=True)
image player 402f = im.Flip("characters/player/char_player_402.png", horizontal=True)
image player 403f = im.Flip("characters/player/char_player_403.png", horizontal=True)
image player 428f = im.Flip("characters/player/char_player_428.png", horizontal=True)
image player 430f = im.Flip("characters/player/char_player_430.png", horizontal=True)
image player 430bf = im.Flip("characters/player/char_player_430b.png", horizontal=True)
image player 434f = im.Flip("characters/player/char_player_434.png", horizontal=True)
image player 435f = im.Flip("characters/player/char_player_435.png", horizontal=True)
image player 444f = im.Flip("characters/player/char_player_444.png", horizontal=True)
image players robe f = im.Flip("characters/player/char_player_445.png", horizontal=True)
image player 455f = im.Flip("characters/player/char_player_455.png", horizontal=True)
image player 456f = im.Flip("characters/player/char_player_456.png", horizontal=True)
image player 457f = im.Flip("characters/player/char_player_457.png", horizontal=True)
image player 458f = im.Flip("characters/player/char_player_458.png", horizontal=True)
image player 459f = im.Flip("characters/player/char_player_459.png", horizontal=True)
image player 460f = im.Flip("characters/player/char_player_460.png", horizontal=True)
image player 461f = im.Flip("characters/player/char_player_461.png", horizontal=True)
image player 494f = im.Flip("characters/player/char_player_494.png", horizontal=True)
image player 495f = im.Flip("characters/player/char_player_495.png", horizontal=True)
image player 503f = im.Flip("characters/player/char_player_503.png", horizontal=True)
image player 504f = im.Flip("characters/player/char_player_504.png", horizontal=True)
image player 507f = im.Flip("characters/player/char_player_507.png", horizontal=True)
image player 508f = im.Flip("characters/player/char_player_508.png", horizontal=True)
image player 521f = im.Flip("characters/player/char_player_521.png", horizontal=True)
image player 562f = im.Flip("characters/player/char_player_562.png", horizontal=True)
image player 563f = im.Flip("characters/player/char_player_563.png", horizontal=True)
image player 564f = im.Flip("characters/player/char_player_564.png", horizontal=True)
image player 565f = im.Flip("characters/player/char_player_565.png", horizontal=True)
image player 566f = im.Flip("characters/player/char_player_566.png", horizontal=True)
image player 567f = im.Flip("characters/player/char_player_567.png", horizontal=True)
image player 567bf = im.Flip("characters/player/char_player_567b.png", horizontal=True)
image player 567cf = im.Flip("characters/player/char_player_567c.png", horizontal=True)
image player 576f = im.Flip("characters/player/char_player_576.png", horizontal=True)
image player 577f = im.Flip("characters/player/char_player_577.png", horizontal=True)
image player 577bf = im.Flip("characters/player/char_player_577b.png", horizontal=True)
image player 577cf = im.Flip("characters/player/char_player_577c.png", horizontal=True)
image player 577df = im.Flip("characters/player/char_player_577d.png", horizontal=True)
image player 638bf = im.Flip("characters/player/char_player_638b.png", xoffset=-10, horizontal=True)
image player_outfit bb 638ef = im.Flip("characters/player/char_player_638e.png", horizontal=True)
image player 642f = im.Flip("characters/player/char_player_642.png",xoffset=-21, horizontal=True)
image player 650f = im.Flip("characters/player/char_player_650.png", horizontal=True)
image player 654f = im.Flip("characters/player/char_player_654.png", horizontal=True)
image player 654bf = im.Flip("characters/player/char_player_654b.png", horizontal=True)
image player 658f = im.Flip("characters/player/char_player_658.png", horizontal=True)

image player_wet_f = im.Flip("characters/player/char_player_wet.png",xoffset=-48,yoffset=-328, horizontal=True)

image playerf 1f = im.Flip("characters/player/char_player_front_01.png", horizontal=True)
image playerf 1bf = im.Flip("characters/player/char_player_front_01b.png", horizontal=True)
image playerf 2flip = im.Flip("characters/player/char_player_front_02.png", horizontal=True)
image playerf 2bf = im.Flip("characters/player/char_player_front_02b.png", horizontal=True)
image playerf 2cf = im.Flip("characters/player/char_player_front_02c.png", horizontal=True)
image playerf 2df = im.Flip("characters/player/char_player_front_02d.png", horizontal=True)
image playerf 2ef = im.Flip("characters/player/char_player_front_02e.png", horizontal=True)
image playerf 2ff = im.Flip("characters/player/char_player_front_02f.png", horizontal=True)
image playerf 3f = im.Flip("characters/player/char_player_front_03.png", horizontal=True)
image playerf 3bf = im.Flip("characters/player/char_player_front_03b.png", horizontal=True)
image playerf 3cf = im.Flip("characters/player/char_player_front_03c.png", horizontal=True)
image playerf 4flip = im.Flip("characters/player/char_player_front_04.png", horizontal=True)
image playerf 4bf = im.Flip("characters/player/char_player_front_04b.png", horizontal=True)
image playerf 4cf = im.Flip("characters/player/char_player_front_04c.png", horizontal=True)
image playerf 4df = im.Flip("characters/player/char_player_front_04d.png", horizontal=True)
image playerf 4ef = im.Flip("characters/player/char_player_front_04e.png", horizontal=True)
image playerf 4ff = im.Flip("characters/player/char_player_front_04f.png", horizontal=True)
image playerf 4gf = im.Flip("characters/player/char_player_front_04g.png", horizontal=True)
image playerf 4hf = im.Flip("characters/player/char_player_front_04h.png", horizontal=True)
image playerf 5f = im.Flip("characters/player/char_player_front_05.png", horizontal=True)
image playerf 5bf = im.Flip("characters/player/char_player_front_05b.png", horizontal=True)
image playerf 6f = im.Flip("characters/player/char_player_front_06.png", horizontal=True)

image playerfa 1f = im.Flip("characters/player/char_player_front_arms_01.png", horizontal=True)
image playerfa 2f = im.Flip("characters/player/char_player_front_arms_02.png", horizontal=True)

image playerfb 1f = im.Flip("characters/player/char_player_front_boner_01.png", horizontal=True)
image playerfb 2f = im.Flip("characters/player/char_player_front_boner_02.png", horizontal=True)
image playerfb 3f = im.Flip("characters/player/char_player_front_boner_03.png", horizontal=True)



image jersey 10f = im.Flip("characters/jersey/char_jersey_10.png", horizontal=True)
image jersey 11f = im.Flip("characters/jersey/char_jersey_11.png", horizontal=True)
image jersey 12f = im.Flip("characters/jersey/char_jersey_12.png", horizontal=True)
image jersey 13f = im.Flip("characters/jersey/char_jersey_13.png", horizontal=True)
image jersey 17f = im.Flip("characters/jersey/char_jersey_17.png", horizontal=True)
image jersey 18f = im.Flip("characters/jersey/char_jersey_18.png", horizontal=True)
image jersey 19f = im.Flip("characters/jersey/char_jersey_19.png", horizontal=True)
image jersey 20f = im.Flip("characters/jersey/char_jersey_20.png", horizontal=True)
image jersey 22f = im.Flip("characters/jersey/char_jersey_22.png", horizontal=True)
image jersey 23f = im.Flip("characters/jersey/char_jersey_23.png", horizontal=True)
image jersey 27f = im.Flip("characters/jersey/char_jersey_27.png", horizontal=True)
image jersey 28f = im.Flip("characters/jersey/char_jersey_28.png", horizontal=True)
image jersey 29f = im.Flip("characters/jersey/char_jersey_29.png", horizontal=True)
image jersey 30f = im.Flip("characters/jersey/char_jersey_30.png", horizontal=True)
image jersey 31f = im.Flip("characters/jersey/char_jersey_31.png", horizontal=True)
image jersey 32f = im.Flip("characters/jersey/char_jersey_32.png", horizontal=True)


image master 2f = im.Flip("characters/master/char_master_02.png", horizontal=True)
image master 3f = im.Flip("characters/master/char_master_03.png", horizontal=True)
image master 4f = im.Flip("characters/master/char_master_04.png", horizontal=True)
image master 6f = im.Flip("characters/master/char_master_06.png", horizontal=True)
image master 10f = im.Flip("characters/master/char_master_10.png", horizontal=True)


image mia 7f = im.Flip("characters/mia/char_mia_07.png", horizontal=True)
image mia 8f = im.Flip("characters/mia/char_mia_08.png", horizontal=True)
image mia 9f = im.Flip("characters/mia/char_mia_09.png", horizontal=True)
image mia 10f = im.Flip("characters/mia/char_mia_10.png", horizontal=True)
image mia 12f = im.Flip("characters/mia/char_mia_12.png", horizontal=True)
image mia 30f = im.Flip("characters/mia/char_mia_30.png", horizontal=True)
image mia 40f = im.Flip("characters/mia/char_mia_40.png", horizontal=True)
image mia 41f = im.Flip("characters/mia/char_mia_41.png", horizontal=True)
image mia 42f = im.Flip("characters/mia/char_mia_42.png", horizontal=True)
image mia 43f = im.Flip("characters/mia/char_mia_43.png", horizontal=True)
image mia 44f = im.Flip("characters/mia/char_mia_44.png", horizontal=True)
image mia 45f = im.Flip("characters/mia/char_mia_45.png", horizontal=True)
image mia 46f = im.Flip("characters/mia/char_mia_46.png", horizontal=True)
image mia 47f = im.Flip("characters/mia/char_mia_47.png", horizontal=True)
image mia 48f = im.Flip("characters/mia/char_mia_48.png", horizontal=True)

image mial 1f = im.Flip("characters/mia/char_mia_labcoat_01.png", xoffset=-21, horizontal=True)


image helen 1f = im.Flip("characters/helen/char_helen_01.png", horizontal=True)
image helen 5f = im.Flip("characters/helen/char_helen_05.png", horizontal=True)
image helen 6f = im.Flip("characters/helen/char_helen_06.png", horizontal=True)
image helen 7f = im.Flip("characters/helen/char_helen_07.png", horizontal=True)
image helen 8f = im.Flip("characters/helen/char_helen_08.png", horizontal=True)
image helen 9f = im.Flip("characters/helen/char_helen_09.png", horizontal=True)
image helen 10f = im.Flip("characters/helen/char_helen_10.png", horizontal=True)
image helen 11f = im.Flip("characters/helen/char_helen_11.png", horizontal=True)


image harold 1f = im.Flip("characters/harold/char_harold_01.png", horizontal=True)
image harold 2f = im.Flip("characters/harold/char_harold_02.png", horizontal=True)
image harold 3f = im.Flip("characters/harold/char_harold_03.png", horizontal=True)
image harold 4f = im.Flip("characters/harold/char_harold_04.png", horizontal=True)
image harold 25f = im.Flip("characters/harold/char_harold_25.png", horizontal=True)
image harold 26f = im.Flip("characters/harold/char_harold_26.png", horizontal=True)


image debbie 1f = im.Flip("characters/debbie/char_debbie_01.png", horizontal=True)
image debbie 2f = im.Flip("characters/debbie/char_debbie_02.png", horizontal=True)
image debbie 3f = im.Flip("characters/debbie/char_debbie_03.png", horizontal=True)
image debbie 13f = im.Flip( "characters/debbie/char_debbie_13.png", horizontal=True)
image debbie 14f = im.Flip( "characters/debbie/char_debbie_14.png", horizontal=True)
image debbie 14bf = im.Flip("characters/debbie/char_debbie_14b.png", horizontal=True)
image debbie 15f = im.Flip("characters/debbie/char_debbie_15.png", horizontal=True)
image debbie 16f = im.Flip("characters/debbie/char_debbie_16.png", horizontal=True)
image debbie 17f = im.Flip("characters/debbie/char_debbie_17.png", horizontal=True)
image debbie 18f = im.Flip("characters/debbie/char_debbie_18.png", horizontal=True)
image debbie 19f = im.Flip("characters/debbie/char_debbie_19.png", horizontal=True)
image debbie 20f = im.Flip("characters/debbie/char_debbie_20.png", horizontal=True)
image debbie 38f = im.Flip("characters/debbie/char_debbie_38.png", horizontal=True)
image debbie 39f = im.Flip("characters/debbie/char_debbie_39.png", horizontal=True)
image debbie 59f = im.Flip("characters/debbie/char_debbie_59.png", horizontal=True)
image debbie 60f = im.Flip("characters/debbie/char_debbie_60.png", horizontal=True)
image debbie 61f = im.Flip("characters/debbie/char_debbie_61.png", horizontal=True)
image debbie 62f = im.Flip("characters/debbie/char_debbie_62.png", horizontal=True)
image debbie 63f = im.Flip("characters/debbie/char_debbie_63.png", horizontal=True)
image debbie 91f = im.Flip("characters/debbie/char_debbie_91.png", horizontal=True)
image debbie 92f = im.Flip("characters/debbie/char_debbie_92.png", horizontal=True)
image debbie 93f = im.Flip("characters/debbie/char_debbie_93.png", horizontal=True)
image debbie 125f = im.Flip("characters/debbie/char_debbie_125.png", horizontal=True)
image debbie 164f = im.Flip("characters/debbie/char_debbie_164.png", horizontal=True)
image debbie 165f = im.Flip("characters/debbie/char_debbie_165.png", horizontal=True)
image debbie 166f = im.Flip("characters/debbie/char_debbie_166.png", horizontal=True)
image debbie 168f = im.Flip("characters/debbie/char_debbie_168.png", horizontal=True)
image debbie 169f = im.Flip("characters/debbie/char_debbie_169.png", horizontal=True)
image debbie 169bf = im.Flip("characters/debbie/char_debbie_169b.png", horizontal=True)
image mneck 1f = im.Flip("characters/debbie/char_debbie_176.png", horizontal=True)
image debbie 183bf = im.Flip("characters/debbie/char_debbie_183b.png", horizontal=True)
image debbie 184cf = im.Flip("characters/debbie/char_debbie_184c.png", horizontal=True)
image debbie 184df = im.Flip("characters/debbie/char_debbie_184d.png", horizontal=True)
image debbie 188f = im.Flip("characters/debbie/char_debbie_188.png",xoffset=130, horizontal=True)
image debbie 189f = im.Flip("characters/debbie/char_debbie_189.png",xoffset=130, horizontal=True)
image debbie 190f = im.Flip("characters/debbie/char_debbie_190.png", horizontal=True)
image debbie 191f = im.Flip("characters/debbie/char_debbie_191.png", horizontal=True)
image debbie_robe 191bf = im.Flip("characters/debbie/char_debbie_191b.png",xoffset=-241,yoffset=-42, horizontal=True)
image debbie 192f = im.Flip("characters/debbie/char_debbie_192.png", horizontal=True)
image debbie 193f = im.Flip("characters/debbie/char_debbie_193.png", horizontal=True)
image player finger 193bf = im.Flip("characters/debbie/char_debbie_193b.png",xoffset=41,yoffset=-1, horizontal=True)
image debbie 194f = im.Flip("characters/debbie/char_debbie_194.png", horizontal=True)
image debbie_robe 194bf = im.Flip("characters/debbie/char_debbie_194b.png",xoffset=-268,yoffset=-42, horizontal=True)
image debbie 195f = im.Flip("characters/debbie/char_debbie_195.png", horizontal=True)
image debbie_robe 195bf = im.Flip("characters/debbie/char_debbie_195b.png",xoffset=-268,yoffset=-40, horizontal=True)
image debbie 196f = im.Flip("characters/debbie/char_debbie_196.png", horizontal=True)
image debbie_robe 196bf = im.Flip("characters/debbie/char_debbie_196b.png",xoffset=-269,yoffset=-39, horizontal=True)
image debbie 197f = im.Flip("characters/debbie/char_debbie_197.png",yoffset=-29, horizontal=True)
image debbie_robe 197bf = im.Flip("characters/debbie/char_debbie_197b.png",xoffset=-279,yoffset=-49, horizontal=True)
image debbie 197cf = im.Flip("characters/debbie/char_debbie_197c.png",yoffset=-24, horizontal=True)
image debbie 197df = im.Flip("characters/debbie/char_debbie_197d.png",yoffset=-24, horizontal=True)
image debbie 197ef = im.Flip("characters/debbie/char_debbie_197e.png",yoffset=-24, horizontal=True)
image debbie 197ff = im.Flip("characters/debbie/char_debbie_197f.png",yoffset=-24, horizontal=True)
image debbie 208f = im.Flip("characters/debbie/char_debbie_208.png", horizontal=True)

image debbief 1f = im.Flip("characters/debbie/char_debbie_front_01.png", horizontal=True)
image debbief 2f = im.Flip("characters/debbie/char_debbie_front_02.png", horizontal=True)
image debbief 2bf = im.Flip("characters/debbie/char_debbie_front_02b.png", horizontal=True)
image debbief 3f = im.Flip("characters/debbie/char_debbie_front_03.png", horizontal=True)
image debbief 3bf = im.Flip("characters/debbie/char_debbie_front_03b.png", horizontal=True)
image debbief 4f = im.Flip("characters/debbie/char_debbie_front_04.png", horizontal=True)
image debbief 4bf = im.Flip("characters/debbie/char_debbie_front_04b.png", horizontal=True)
image debbief 4cf = im.Flip("characters/debbie/char_debbie_front_04c.png", horizontal=True)
image debbief 5flip = im.Flip("characters/debbie/char_debbie_front_05.png", horizontal=True)
image debbief 5bf = im.Flip("characters/debbie/char_debbie_front_05b.png", horizontal=True)
image debbief 5cf = im.Flip("characters/debbie/char_debbie_front_05c.png", horizontal=True)
image debbief 5df = im.Flip("characters/debbie/char_debbie_front_05d.png", horizontal=True)
image debbief 5ef = im.Flip("characters/debbie/char_debbie_front_05e.png", horizontal=True)
image debbief 5ff = im.Flip("characters/debbie/char_debbie_front_05f.png", horizontal=True)
image debbief 5gf = im.Flip("characters/debbie/char_debbie_front_05g.png", horizontal=True)
image debbief 6f = im.Flip("characters/debbie/char_debbie_front_06.png", horizontal=True)
image debbief 7f = im.Flip("characters/debbie/char_debbie_front_07.png", horizontal=True)
image debbief 7bf = im.Flip("characters/debbie/char_debbie_front_07b.png", horizontal=True)
image debbief 8flip = im.Flip("characters/debbie/char_debbie_front_08.png", horizontal=True)
image debbief 8bf = im.Flip("characters/debbie/char_debbie_front_08b.png", horizontal=True)
image debbief 8cf = im.Flip("characters/debbie/char_debbie_front_08c.png", horizontal=True)
image debbief 8df = im.Flip("characters/debbie/char_debbie_front_08d.png", horizontal=True)
image debbief 8ef = im.Flip("characters/debbie/char_debbie_front_08e.png", horizontal=True)
image debbief 8ff = im.Flip("characters/debbie/char_debbie_front_08f.png", horizontal=True)
image debbief 8gf = im.Flip("characters/debbie/char_debbie_front_08g.png", horizontal=True)
image debbief 9f = im.Flip("characters/debbie/char_debbie_front_09.png", horizontal=True)
image debbief 10f = im.Flip("characters/debbie/char_debbie_front_10.png", horizontal=True)
image debbief 11f = im.Flip("characters/debbie/char_debbie_front_11.png", horizontal=True)
image debbief 12f = im.Flip("characters/debbie/char_debbie_front_12.png", horizontal=True)

image debbiefa 1f = im.Flip("characters/debbie/char_debbie_front_arms_01.png", horizontal=True)
image debbiefa 2f = im.Flip("characters/debbie/char_debbie_front_arms_02.png", horizontal=True)
image debbiefa 3f = im.Flip("characters/debbie/char_debbie_front_arms_03.png", horizontal=True)
image debbiefa 3bf = im.Flip("characters/debbie/char_debbie_front_arms_03b.png", horizontal=True)
image debbiefa 4f = im.Flip("characters/debbie/char_debbie_front_arms_04.png", horizontal=True)
image debbiefa 5f = im.Flip("characters/debbie/char_debbie_front_arms_05.png", horizontal=True)
image debbiefa 5bf = im.Flip("characters/debbie/char_debbie_front_arms_05b.png", horizontal=True)
image debbiefa 5cf = im.Flip("characters/debbie/char_debbie_front_arms_05c.png", horizontal=True)


image dexter 16f = im.Flip("characters/dexter/char_dexter_16.png", horizontal=True)
image dexter 16bf = im.Flip("characters/dexter/char_dexter_16b.png", horizontal=True)



image jenny 1f = im.Flip("characters/jenny/char_jenny_01.png", horizontal=True)
image jenny 2f = im.Flip("characters/jenny/char_jenny_02.png", horizontal=True)
image jenny 3f = im.Flip("characters/jenny/char_jenny_03.png", horizontal=True)
image jenny 6f = im.Flip("characters/jenny/char_jenny_06.png", horizontal=True)
image jenny 7f = im.Flip("characters/jenny/char_jenny_07.png", horizontal=True)
image jenny 8f = im.Flip("characters/jenny/char_jenny_08.png", horizontal=True)
image jenny 9f = im.Flip("characters/jenny/char_jenny_09.png", horizontal=True)
image jenny 10f = im.Flip("characters/jenny/char_jenny_10.png", horizontal=True)
image jenny 11f = im.Flip("characters/jenny/char_jenny_11.png", horizontal=True)
image jenny 12f = im.Flip("characters/jenny/char_jenny_12.png", horizontal=True)
image jenny 13f = im.Flip("characters/jenny/char_jenny_13.png", horizontal=True)
image jenny 14f = im.Flip("characters/jenny/char_jenny_14.png", horizontal=True)
image jenny 15f = im.Flip("characters/jenny/char_jenny_15.png", horizontal=True)
image jenny 16f = im.Flip("characters/jenny/char_jenny_16.png", horizontal=True)
image jenny 17f = im.Flip("characters/jenny/char_jenny_17.png", horizontal=True)
image jenny 18f = im.Flip("characters/jenny/char_jenny_18.png", horizontal=True)
image jenny 19f = im.Flip("characters/jenny/char_jenny_19.png", horizontal=True)
image jenny 49f = im.Flip("characters/jenny/char_jenny_49.png", horizontal=True)


image judith 1f = im.Flip("characters/judith/char_judith_01.png", horizontal=True)
image judith 2f = im.Flip("characters/judith/char_judith_02.png", horizontal=True)
image judith 3f = im.Flip("characters/judith/char_judith_03.png", horizontal=True)
image judith 4f = im.Flip("characters/judith/char_judith_04.png", horizontal=True)
image judith 5f = im.Flip("characters/judith/char_judith_05.png", horizontal=True)
image judith 6f = im.Flip("characters/judith/char_judith_06.png", horizontal=True)
image judith 7f = im.Flip("characters/judith/char_judith_07.png", horizontal=True)
image judith 8f = im.Flip("characters/judith/char_judith_08.png", horizontal=True)
image judith 9f = im.Flip("characters/judith/char_judith_09.png", horizontal=True)
image judith 10f = im.Flip("characters/judith/char_judith_10.png", horizontal=True)


image erik 1f = im.Flip("characters/erik/char_erik_01.png", horizontal=True)
image erik 2f = im.Flip("characters/erik/char_erik_02.png", horizontal=True)
image erik 3f = im.Flip("characters/erik/char_erik_03.png", horizontal=True)
image erik 3bf = im.Flip("characters/erik/char_erik_03b.png", horizontal=True)
image erik 4f = im.Flip("characters/erik/char_erik_04.png", horizontal=True)
image erik 5f = im.Flip("characters/erik/char_erik_05.png", horizontal=True)
image erik 5bf = im.Flip("characters/erik/char_erik_05b.png", horizontal=True)
image erik 6f = im.Flip("characters/erik/char_erik_06.png", horizontal=True)
image erik 7f = im.Flip("characters/erik/char_erik_07.png", horizontal=True)
image erik 8f = im.Flip("characters/erik/char_erik_08.png", horizontal=True)
image erik 9f = im.Flip("characters/erik/char_erik_09.png", horizontal=True)
image erik 10f = im.Flip("characters/erik/char_erik_10.png", horizontal=True)
image erik 11f = im.Flip("characters/erik/char_erik_11.png", horizontal=True)
image erik 12f = im.Flip("characters/erik/char_erik_12.png", horizontal=True)
image erik 13f = im.Flip("characters/erik/char_erik_13.png", horizontal=True)
image erik 14f = im.Flip("characters/erik/char_erik_14.png", horizontal=True)
image erik 15f = im.Flip( "characters/erik/char_erik_15.png", horizontal=True)
image erik 15bf = im.Flip( "characters/erik/char_erik_15b.png", horizontal=True)
image erik 16f = im.Flip("characters/erik/char_erik_16.png", horizontal=True,xoffset=-13)
image erik 17f = im.Flip("characters/erik/char_erik_17.png", horizontal=True)
image erik 18f = im.Flip("characters/erik/char_erik_18.png", horizontal=True)
image erik 19f = im.Flip("characters/erik/char_erik_19.png", horizontal=True)
image erik 50f = im.Flip("characters/erik/char_erik_50.png", horizontal=True)
image erik 51f = im.Flip("characters/erik/char_erik_51.png", horizontal=True)
image erik 52f = im.Flip("characters/erik/char_erik_52.png", horizontal=True)
image erik 53f = im.Flip("characters/erik/char_erik_53.png", horizontal=True)
image erik 55f = im.Flip("characters/erik/char_erik_55.png", horizontal=True)
image erik 56f = im.Flip( "characters/erik/char_erik_56.png", horizontal=True)
image erik 57f = im.Flip( "characters/erik/char_erik_57.png", horizontal=True)
image erik 58f = im.Flip( "characters/erik/char_erik_58.png", horizontal=True)
image erik 59f = im.Flip("characters/erik/char_erik_59.png", horizontal=True)
image erik 60f = im.Flip("characters/erik/char_erik_60.png", horizontal=True)
image erik 64f = im.Flip("characters/erik/char_erik_64.png", horizontal=True)
image erik 65f = im.Flip("characters/erik/char_erik_65.png", horizontal=True)
image erik 66f = im.Flip("characters/erik/char_erik_66.png", horizontal=True)
image erik 67f = im.Flip("characters/erik/char_erik_67.png",xoffset=51, horizontal=True)
image erik 68f = im.Flip("characters/erik/char_erik_68.png",xoffset=51, horizontal=True)
image erik 69f = im.Flip("characters/erik/char_erik_69.png",xoffset=51, horizontal=True)
image erik 70f = im.Flip("characters/erik/char_erik_70.png",xoffset=51, horizontal=True)
image erik 71f = im.Flip("characters/erik/char_erik_71.png", horizontal=True)

image erikl 1f = im.Flip("characters/erik/char_erik_labcoat_01.png", xoffset=34, horizontal=True)


image principal 1f = im.Flip( "characters/principal/char_principal_01.png", horizontal=True)
image principal 2f = im.Flip( "characters/principal/char_principal_02.png", horizontal=True)
image principal 3f = im.Flip( "characters/principal/char_principal_03.png", horizontal=True)
image principal 4f = im.Flip( "characters/principal/char_principal_04.png", horizontal=True)
image principal 5f = im.Flip( "characters/principal/char_principal_05.png", horizontal=True)
image principal 6f = im.Flip( "characters/principal/char_principal_06.png", horizontal=True)
image principal 7f = im.Flip( "characters/principal/char_principal_07.png", horizontal=True)
image principal 8f = im.Flip( "characters/principal/char_principal_08.png", horizontal=True)
image principal 9f = im.Flip( "characters/principal/char_principal_09.png", horizontal=True)
image principal 10f = im.Flip( "characters/principal/char_principal_10.png", horizontal=True)
image principal 11f = im.Flip( "characters/principal/char_principal_11.png", horizontal=True)
image principal 12f = im.Flip( "characters/principal/char_principal_12.png", horizontal=True)
image principal 13f = im.Flip( "characters/principal/char_principal_13.png", horizontal=True)
image principal 14f = im.Flip( "characters/principal/char_principal_14.png", horizontal=True)
image principal 15f = im.Flip( "characters/principal/char_principal_15.png", horizontal=True)
image principal 16f = im.Flip( "characters/principal/char_principal_16.png", horizontal=True)
image principal 17f = im.Flip( "characters/principal/char_principal_17.png", horizontal=True)
image principal 18f = im.Flip( "characters/principal/char_principal_18.png", horizontal=True)
image principal 19f = im.Flip( "characters/principal/char_principal_19.png", horizontal=True)
image principal 20f = im.Flip( "characters/principal/char_principal_20.png", horizontal=True)
image principal 21f = im.Flip( "characters/principal/char_principal_21.png", horizontal=True)
image principal 22f = im.Flip( "characters/principal/char_principal_22.png", horizontal=True)
image principal 23f = im.Flip( "characters/principal/char_principal_23.png", horizontal=True)
image principal 24f = im.Flip( "characters/principal/char_principal_24.png", horizontal=True)
image principal 25f = im.Flip( "characters/principal/char_principal_25.png", horizontal=True)
image principal 26f = im.Flip( "characters/principal/char_principal_26.png", horizontal=True)
image principal 27f = im.Flip( "characters/principal/char_principal_27.png", horizontal=True)
image principal 28f = im.Flip( "characters/principal/char_principal_28.png", horizontal=True)
image principal 29f = im.Flip("characters/principal/char_principal_29.png",xoffset=70, horizontal=True)


image eve 1f = im.Flip("characters/eve/char_eve_01.png", horizontal=True)
image eve 1bf = im.Flip("characters/eve/char_eve_01b.png", horizontal=True)
image eve 1cf = im.Flip("characters/eve/char_eve_01c.png", horizontal=True)
image eve 2bf = im.Flip("characters/eve/char_eve_02b.png", horizontal=True)
image eve 5f = im.Flip("characters/eve/char_eve_05.png", horizontal=True)
image eve 6f = im.Flip("characters/eve/char_eve_06.png", horizontal=True)
image eve 9f = im.Flip("characters/eve/char_eve_09.png", horizontal=True)
image eve 11f = im.Flip("characters/eve/char_eve_11.png", horizontal=True)
image eve 12f = im.Flip("characters/eve/char_eve_12.png", horizontal=True)
image eve 18f = im.Flip("characters/eve/char_eve_18.png", horizontal=True, xoffset=-11)
image eve 19f = im.Flip("characters/eve/char_eve_19.png", horizontal=True)
image eve 20f = im.Flip("characters/eve/char_eve_20.png", horizontal=True)
image eve 25f = im.Flip("characters/eve/char_eve_25.png", horizontal=True)


image yumi 1f = im.Flip("characters/yumi/char_yumi_01.png", horizontal=True)
image yumi 2f = im.Flip("characters/yumi/char_yumi_02.png", horizontal=True)
image yumi 5f = im.Flip("characters/yumi/char_yumi_05.png", horizontal=True)
image yumi 6f = im.Flip("characters/yumi/char_yumi_06.png", horizontal=True)
image yum 12f = im.Flip("characters/yumi/char_yumi_12.png", horizontal=True)
image yum 13f = im.Flip("characters/yumi/char_yumi_13.png", horizontal=True)
image yum 14f = im.Flip("characters/yumi/char_yumi_14.png", horizontal=True)


image sara 4f = im.Flip("characters/sara/char_sara_04.png", horizontal=True)
image sara 5f = im.Flip("characters/sara/char_sara_05.png", horizontal=True)


image tstand 1f = im.Flip("characters/terry/char_terry_standing_01.png", horizontal=True)
image tstand 2f = im.Flip("characters/terry/char_terry_standing_02.png", horizontal=True)
image tstand 3f = im.Flip("characters/terry/char_terry_standing_03.png", horizontal=True)


image titty 1f = im.Flip( "characters/titty/char_titty_01.png", horizontal=True)


image mrsj 1f = im.Flip( "characters/mrsj/char_mrsj_01.png", horizontal=True)
image mrsj 2f = im.Flip( "characters/mrsj/char_mrsj_02.png", horizontal=True)
image mrsj 3f = im.Flip( "characters/mrsj/char_mrsj_03.png", horizontal=True)
image mrsj 4f = im.Flip( "characters/mrsj/char_mrsj_04.png", horizontal=True)
image mrsj 5f = im.Flip( "characters/mrsj/char_mrsj_05.png", horizontal=True)
image mrsj 6f = im.Flip( "characters/mrsj/char_mrsj_06.png", horizontal=True)
image mrsj 7f = im.Flip( "characters/mrsj/char_mrsj_07.png", horizontal=True)
image mrsj 8f = im.Flip( "characters/mrsj/char_mrsj_08.png", horizontal=True)
image mrsj 9f = im.Flip( "characters/mrsj/char_mrsj_09.png", horizontal=True)
image mrsj 10f = im.Flip( "characters/mrsj/char_mrsj_10.png", horizontal=True)
image mrsj 11f = im.Flip( "characters/mrsj/char_mrsj_11.png", horizontal=True)
image mrsj 12f = im.Flip( "characters/mrsj/char_mrsj_12.png", horizontal=True)
image mrsj 13f = im.Flip( "characters/mrsj/char_mrsj_13.png", horizontal=True)
image mrsj 14f = im.Flip( "characters/mrsj/char_mrsj_14.png", horizontal=True)
image mrsj 15f = im.Flip( "characters/mrsj/char_mrsj_15.png", horizontal=True)
image mrsj 16f = im.Flip( "characters/mrsj/char_mrsj_16.png", horizontal=True)
image mrsj 17f = im.Flip( "characters/mrsj/char_mrsj_17.png", horizontal=True)
image mrsj 18f = im.Flip( "characters/mrsj/char_mrsj_18.png", horizontal=True)
image mrsj 19f = im.Flip( "characters/mrsj/char_mrsj_19.png", horizontal=True)
image mrsj 20f = im.Flip( "characters/mrsj/char_mrsj_20.png", horizontal=True)
image mrsj 21f = im.Flip( "characters/mrsj/char_mrsj_21.png", horizontal=True)
image mrsj 22f = im.Flip( "characters/mrsj/char_mrsj_22.png", horizontal=True)
image mrsj 23f = im.Flip( "characters/mrsj/char_mrsj_23.png", horizontal=True)
image mrsj 24f = im.Flip( "characters/mrsj/char_mrsj_24.png", horizontal=True)
image mrsj 25f = im.Flip( "characters/mrsj/char_mrsj_25.png", horizontal=True)
image mrsj 26f = im.Flip( "characters/mrsj/char_mrsj_26.png", horizontal=True)
image mrsj 27f = im.Flip( "characters/mrsj/char_mrsj_27.png", horizontal=True)
image mrsj 28f = im.Flip( "characters/mrsj/char_mrsj_28.png", horizontal=True)
image mrsj 29f = im.Flip( "characters/mrsj/char_mrsj_29.png", horizontal=True)
image mrsj 30f = im.Flip( "characters/mrsj/char_mrsj_30.png", horizontal=True)
image mrsj 31f = im.Flip( "characters/mrsj/char_mrsj_31.png", horizontal=True)
image mrsj 32f = im.Flip( "characters/mrsj/char_mrsj_32.png", horizontal=True)
image mrsj 33f = im.Flip( "characters/mrsj/char_mrsj_33.png", horizontal=True)
image mrsj 34f = im.Flip( "characters/mrsj/char_mrsj_34.png", horizontal=True)
image mrsj 35f = im.Flip( "characters/mrsj/char_mrsj_35.png", horizontal=True)
image mrsj 38f = im.Flip("characters/mrsj/char_mrsj_38.png", horizontal=True)
image mrsj 49f = im.Flip("characters/mrsj/char_mrsj_49.png", horizontal=True)
image mrsj 50f = im.Flip("characters/mrsj/char_mrsj_50.png", horizontal=True)
image mrsj 52f = im.Flip("characters/mrsj/char_mrsj_52.png", horizontal=True)


image kevin 9bf = im.Flip("characters/kevin/char_kevin_09b.png", horizontal=True)
image kevin 14f = im.Flip("characters/kevin/char_kevin_14.png", horizontal=True)
image kevin 15f = im.Flip("characters/kevin/char_kevin_15.png", horizontal=True)
image kevin 16f = im.Flip("characters/kevin/char_kevin_16.png", horizontal=True)
image kevin 17f = im.Flip("characters/kevin/char_kevin_17.png", horizontal=True)
image kevin 18f = im.Flip("characters/kevin/char_kevin_18.png", horizontal=True)
image kevin 23f = im.Flip("characters/kevin/char_kevin_23.png", horizontal=True)
image kevin 24f = im.Flip("characters/kevin/char_kevin_24.png", horizontal=True)
image kevin 24bf = im.Flip("characters/kevin/char_kevin_24b.png", horizontal=True)
image kevin 32f = im.Flip("characters/kevin/char_kevin_32.png", horizontal=True)
image kevin 34f = im.Flip("characters/kevin/char_kevin_34.png",xoffset=41, horizontal=True)
image kevin 34bf = im.Flip("characters/kevin/char_kevin_34b.png",xoffset=41, horizontal=True)
image kevin 35f = im.Flip("characters/kevin/char_kevin_35.png", horizontal=True)
image kevin 36f = im.Flip("characters/kevin/char_kevin_36.png", horizontal=True)
image kevin 36bf = im.Flip("characters/kevin/char_kevin_36b.png", horizontal=True)


image harold 1f = im.Flip( "characters/harold/char_harold_01.png", horizontal=True)
image harold 3f = im.Flip( "characters/harold/char_harold_03.png", horizontal=True)


image henchman1 6f = im.Flip("characters/henchman/char_henchman_06.png", horizontal=True)


image annie 8f = im.Flip( "characters/annie/char_annie_08.png", horizontal=True)
image annie 22f = im.Flip("characters/annie/char_annie_22.png", horizontal=True)
image annie 23f = im.Flip("characters/annie/char_annie_23.png", horizontal=True)


image coach 15f = im.Flip("characters/coach/char_coach_15.png", horizontal=True)
image coach 15cf = im.Flip("characters/coach/char_coach_15c.png", horizontal=True)
image coach 17f = im.Flip("characters/coach/char_coach_17.png",xoffset=4, horizontal=True)
image coach 18f = im.Flip("characters/coach/char_coach_18.png", horizontal=True)
image coach 19f = im.Flip("characters/coach/char_coach_19.png", horizontal=True)



image ang 1f = im.Flip("characters/angelica/char_angelica_01.png", horizontal=True)
image ang 2f = im.Flip("characters/angelica/char_angelica_02.png", horizontal=True)
image ang 5f = im.Flip("characters/angelica/char_angelica_05.png", horizontal=True)
image ang 6f = im.Flip("characters/angelica/char_angelica_06.png", horizontal=True)
image ang 7f = im.Flip("characters/angelica/char_angelica_07.png", horizontal=True)
image ang 8f = im.Flip("characters/angelica/char_angelica_08.png", horizontal=True)
image ang 9f = im.Flip("characters/angelica/char_angelica_09.png", horizontal=True)
image ang 10f = im.Flip("characters/angelica/char_angelica_10.png", horizontal=True)
image ang 17f = im.Flip("characters/angelica/char_angelica_17.png", horizontal=True)
image ang 18f = im.Flip("characters/angelica/char_angelica_18.png", horizontal=True)
image ang 21f = im.Flip("characters/angelica/char_angelica_21.png", horizontal=True)
image ang 22f = im.Flip("characters/angelica/char_angelica_22.png", horizontal=True)
image ang 23f = im.Flip("characters/angelica/char_angelica_23.png", horizontal=True)
image ang 24f = im.Flip("characters/angelica/char_angelica_24.png", horizontal=True)
image ang 25f = im.Flip("characters/angelica/char_angelica_25.png", horizontal=True)
image ang 25bf = im.Flip("characters/angelica/char_angelica_25b.png", horizontal=True)
image ang 26f = im.Flip("characters/angelica/char_angelica_26.png", horizontal=True)
image ang 26bf = im.Flip("characters/angelica/char_angelica_26b.png", horizontal=True)
image ang 33f = im.Flip("characters/angelica/char_angelica_33.png", horizontal=True)
image ang 34f = im.Flip("characters/angelica/char_angelica_34.png", horizontal=True)
image helen whip 3 = im.Flip("characters/angelica/char_angelica_21.png", horizontal=True)


image anna 4f = im.Flip( "characters/anna/char_anna_04.png", horizontal=True)
image anna 5f = im.Flip( "characters/anna/char_anna_05.png", horizontal=True)
image anna 8f = im.Flip( "characters/anna/char_anna_08.png", horizontal=True)
image anna 12f = im.Flip( "characters/anna/char_anna_12.png", horizontal=True)


image chad 1f = im.Flip("characters/chad/char_chad_01.png", horizontal=True)
image chad 5f = im.Flip("characters/chad/char_chad_05.png", horizontal=True)
image chad 6f = im.Flip("characters/chad/char_chad_06.png", horizontal=True)
image chad 12f = im.Flip("characters/chad/char_chad_12.png", horizontal=True)
image chad 13f = im.Flip("characters/chad/char_chad_13.png", horizontal=True)




image becca 1f = im.Flip("characters/becca/char_becca_01.png", horizontal=True)
image becca 2f = im.Flip("characters/becca/char_becca_02.png", horizontal=True)
image becca 2bf = im.Flip("characters/becca/char_becca_02b.png", horizontal=True)
image becca 3f = im.Flip("characters/becca/char_becca_03.png", horizontal=True)
image becca 3bf = im.Flip("characters/becca/char_becca_03b.png", horizontal=True)
image becca 4f = im.Flip("characters/becca/char_becca_04.png", horizontal=True)
image becca 5f = im.Flip("characters/becca/char_becca_05.png", horizontal=True)
image becca 6f = im.Flip("characters/becca/char_becca_06.png", horizontal=True)
image becca 7f = im.Flip("characters/becca/char_becca_07.png", horizontal=True)
image becca 8f = im.Flip("characters/becca/char_becca_08.png", horizontal=True)
image becca 12f = im.Flip("characters/becca/char_becca_12.png", horizontal=True)
image becca 13f = im.Flip("characters/becca/char_becca_13.png", horizontal=True)
image becca 19f = im.Flip("characters/becca/char_becca_19.png", horizontal=True)
image becca 20f = im.Flip("characters/becca/char_becca_20.png", horizontal=True)
image becca 21f = im.Flip("characters/becca/char_becca_21.png", horizontal=True)
image becca 22f = im.Flip("characters/becca/char_becca_22.png", horizontal=True)
image becca 23f = im.Flip("characters/becca/char_becca_23.png", horizontal=True)

image becca front sitting 1f = im.Flip("characters/becca/char_becca_front_01.png",xoffset=-190, horizontal=True)
image becca front sitting 2f = im.Flip("characters/becca/char_becca_front_02.png",xoffset=-190, horizontal=True)
image becca front sitting 3f = im.Flip("characters/becca/char_becca_front_03.png",xoffset=-145, horizontal=True)
image becca front sitting 3bf = im.Flip("characters/becca/char_becca_front_03b.png",xoffset=-145, horizontal=True)

image becca bikini 1f = im.Flip("characters/becca/char_becca_bikini_01.png", horizontal=True)
image becca bikini 1bf = im.Flip("characters/becca/char_becca_bikini_01b.png", horizontal=True)
image becca bikini 2f = im.Flip("characters/becca/char_becca_bikini_02.png", horizontal=True)
image becca bikini 2bf = im.Flip("characters/becca/char_becca_bikini_02b.png", horizontal=True)
image becca bikini 11f = im.Flip("characters/becca/char_becca_bikini_11.png", horizontal=True)
image becca bikini 12f = im.Flip("characters/becca/char_becca_bikini_12.png", horizontal=True)
image becca bikini 17f = im.Flip("characters/becca/char_becca_bikini_17.png", horizontal=True)

image beccas_beach_sidef = im.Flip("characters/becca/char_becca_sex_foursome_side.png", horizontal=True)


image missy 1f = im.Flip("characters/missy/char_missy_01.png", horizontal=True)
image missy 1bf = im.Flip("characters/missy/char_missy_01b.png", horizontal=True)
image missy 2f = im.Flip("characters/missy/char_missy_02.png", horizontal=True)
image missy 2bf = im.Flip("characters/missy/char_missy_02b.png", horizontal=True)
image missy 3f = im.Flip("characters/missy/char_missy_03.png", horizontal=True)
image missy 4f = im.Flip("characters/missy/char_missy_04.png", horizontal=True)
image missy 4bf = im.Flip("characters/missy/char_missy_04b.png", horizontal=True)
image missy 4cf = im.Flip("characters/missy/char_missy_04c.png", horizontal=True)
image missy 6f = im.Flip("characters/missy/char_missy_06.png", horizontal=True)
image missy 7f = im.Flip("characters/missy/char_missy_07.png", horizontal=True)
image missy 8f = im.Flip("characters/missy/char_missy_08.png", horizontal=True)

image missy naked 1f = im.Flip("characters/missy/char_missy_naked_01.png", horizontal=True)
image missy naked 2f = im.Flip("characters/missy/char_missy_naked_02.png", horizontal=True)
image missy naked 3f = im.Flip("characters/missy/char_missy_naked_03.png",xoffset=5, horizontal=True)
image missy naked 4f = im.Flip("characters/missy/char_missy_naked_04.png", horizontal=True)
image missy naked 5f = im.Flip("characters/missy/char_missy_naked_05.png", horizontal=True)
image missy naked 6f = im.Flip("characters/missy/char_missy_naked_06.png", horizontal=True)
image missy naked 7f = im.Flip("characters/missy/char_missy_naked_07.png", horizontal=True)

image missy front sitting 1f = im.Flip("characters/missy/char_missy_front_01.png",xoffset=-170, horizontal=True)
image missy front sitting 2f = im.Flip("characters/missy/char_missy_front_02.png",xoffset=-170, horizontal=True)
image missy front sitting 3f = im.Flip("characters/missy/char_missy_front_03.png",xoffset=-134, horizontal=True)
image missy front sitting 3bf = im.Flip("characters/missy/char_missy_front_03b.png",xoffset=-134, horizontal=True)

image missy_arm front sitting 1f = im.Flip("characters/missy/char_missy_front_arms_01.png",xoffset=-156,yoffset=-375, horizontal=True)

image missy bikini 1f = im.Flip("characters/missy/char_missy_bikini_01.png", horizontal=True)
image missy bikini 2f = im.Flip("characters/missy/char_missy_bikini_02.png", horizontal=True)

image missys_beach_sidef = im.Flip("characters/missy/char_missy_sex_foursome_side.png", horizontal=True)


image kim 4f = im.Flip("characters/kim/char_kim_04.png", horizontal=True)


image teacher 1f = im.Flip("characters/teacher/char_teacher_01.png", horizontal=True)
image teacher 2f = im.Flip("characters/teacher/char_teacher_02.png", horizontal=True)
image teacher 3f = im.Flip("characters/teacher/char_teacher_03.png", horizontal=True)
image teacher 4f = im.Flip("characters/teacher/char_teacher_04.png", horizontal=True)
image teacher 5f = im.Flip("characters/teacher/char_teacher_05.png", horizontal=True)
image teacher 6bf = im.Flip("characters/teacher/char_teacher_06b.png", horizontal=True)
image teacher 7f = im.Flip("characters/teacher/char_teacher_07.png", horizontal=True)
image teacher 12f = im.Flip("characters/teacher/char_teacher_12.png", horizontal=True)
image teacher 18f = im.Flip("characters/teacher/char_teacher_18.png", horizontal=True)
image teacher 19f = im.Flip("characters/teacher/char_teacher_19.png", horizontal=True)
image teacher 20f = im.Flip("characters/teacher/char_teacher_20.png", horizontal=True)
image teacher 24bf = im.Flip("characters/teacher/char_teacher_24b.png", horizontal=True)
image teacher 24cf = im.Flip("characters/teacher/char_teacher_24c.png", horizontal=True)


image coach 1f = im.Flip("characters/coach/char_coach_01.png", horizontal=True)
image coach 2f = im.Flip("characters/coach/char_coach_02.png", horizontal=True)
image coach 3f = im.Flip("characters/coach/char_coach_03.png", horizontal=True)
image coach 4f = im.Flip("characters/coach/char_coach_04.png", horizontal=True)
image coach 6f = im.Flip("characters/coach/char_coach_06.png", horizontal=True)


image jane 1f = im.Flip("characters/librarian/char_librarian_01.png", horizontal=True)
image jane 2f = im.Flip("characters/librarian/char_librarian_02.png", horizontal=True)
image jane 3f = im.Flip("characters/librarian/char_librarian_03.png", horizontal=True)
image jane 4f = im.Flip("characters/librarian/char_librarian_04.png", horizontal=True)
image jane 5f = im.Flip("characters/librarian/char_librarian_05.png", horizontal=True)
image jane 8f = im.Flip("characters/librarian/char_librarian_08.png", horizontal=True)
image jane 12f = im.Flip("characters/librarian/char_librarian_12.png", horizontal=True)
image jane 17f = im.Flip("characters/librarian/char_librarian_17.png", horizontal=True)
image jane 17bf = im.Flip("characters/librarian/char_librarian_17b.png", horizontal=True)
image jane 18f = im.Flip("characters/librarian/char_librarian_18.png", horizontal=True)
image jane 18bf = im.Flip("characters/librarian/char_librarian_18b.png", horizontal=True)
image jane 19f = im.Flip("characters/librarian/char_librarian_19.png", horizontal=True)
image jane 20f = im.Flip("characters/librarian/char_librarian_20.png", horizontal=True)
image jane 21f = im.Flip("characters/librarian/char_librarian_21.png", horizontal=True)
image jane 22f = im.Flip("characters/librarian/char_librarian_22.png", horizontal=True)


image pilly 1f = im.Flip("characters/pilly/char_pilly_01.png", horizontal=True)
image pilly 2f = im.Flip("characters/pilly/char_pilly_02.png", horizontal=True)
image pilly 3f = im.Flip("characters/pilly/char_pilly_03.png", horizontal=True)
image pilly 4f = im.Flip("characters/pilly/char_pilly_04.png", xoffset=-44, horizontal=True)
image pilly 5f = im.Flip("characters/pilly/char_pilly_05.png", horizontal=True)
image pilly 6f = im.Flip("characters/pilly/char_pilly_06.png", horizontal=True)


image june 9f = im.Flip("characters/june/char_june_09.png", horizontal=True)
image june 10f = im.Flip("characters/june/char_june_10.png", horizontal=True)


image roxxy 1f f = im.Flip("characters/roxxy/char_roxxy_01.png", horizontal=True)
image roxxy 1bf = im.Flip("characters/roxxy/char_roxxy_01b.png", horizontal=True)
image roxxy 1if = im.Flip("characters/roxxy/char_roxxy_01i.png", xoffset=67, horizontal=True)
image roxxy 1jf = im.Flip("characters/roxxy/char_roxxy_01j.png", xoffset=67, horizontal=True)
image roxxy 1kf = im.Flip("characters/roxxy/char_roxxy_01k.png", xoffset=33, horizontal=True)
image roxxy 1lf = im.Flip("characters/roxxy/char_roxxy_01l.png", xoffset=67, horizontal=True)
image roxxy 1of = im.Flip("characters/roxxy/char_roxxy_01o.png", xoffset=67, horizontal=True)
image roxxy 1mf = im.Flip("characters/roxxy/char_roxxy_01m.png", xoffset=67, horizontal=True)
image roxxy 1nf = im.Flip("characters/roxxy/char_roxxy_01n.png", xoffset=67, horizontal=True)
image roxxy 2f = im.Flip("characters/roxxy/char_roxxy_02.png", horizontal=True)
image roxxy 2bf = im.Flip("characters/roxxy/char_roxxy_02b.png", horizontal=True)
image roxxy 2cf = im.Flip("characters/roxxy/char_roxxy_02c.png", horizontal=True)
image roxxy 3f = im.Flip("characters/roxxy/char_roxxy_03.png", horizontal=True)
image roxxy 3bf = im.Flip("characters/roxxy/char_roxxy_03b.png", horizontal=True)
image roxxy 3cf = im.Flip("characters/roxxy/char_roxxy_03c.png", horizontal=True)
image roxxy 3df = im.Flip("characters/roxxy/char_roxxy_03d.png", horizontal=True)
image roxxy 3ef = im.Flip("characters/roxxy/char_roxxy_03e.png", horizontal=True)
image roxxy 4f = im.Flip("characters/roxxy/char_roxxy_04.png", horizontal=True)
image roxxy 5f = im.Flip("characters/roxxy/char_roxxy_05.png", horizontal=True)
image roxxy 6f = im.Flip("characters/roxxy/char_roxxy_06.png", horizontal=True)
image roxxy 7f = im.Flip("characters/roxxy/char_roxxy_07.png", horizontal=True)
image roxxy 9f = im.Flip("characters/roxxy/char_roxxy_09.png", horizontal=True)
image roxxy 10f = im.Flip("characters/roxxy/char_roxxy_10.png", horizontal=True)
image roxxy 11f = im.Flip("characters/roxxy/char_roxxy_11.png", horizontal=True)
image roxxy 14f = im.Flip("characters/roxxy/char_roxxy_14.png", horizontal=True)
image roxxy 17bf = im.Flip("characters/roxxy/char_roxxy_17b.png", xoffset=67, horizontal=True)
image roxxy 17cf = im.Flip("characters/roxxy/char_roxxy_17c.png", xoffset=67, horizontal=True)
image roxxy 17df = im.Flip("characters/roxxy/char_roxxy_17d.png", xoffset=67, horizontal=True)
image roxxy 17ef = im.Flip("characters/roxxy/char_roxxy_17e.png", xoffset=67, horizontal=True)
image roxxy 23f = im.Flip("characters/roxxy/char_roxxy_23.png", horizontal=True)
image roxxy 27f = im.Flip("characters/roxxy/char_roxxy_27.png", horizontal=True)
image roxxy 28f = im.Flip("characters/roxxy/char_roxxy_28.png", horizontal=True)
image roxxy 29f = im.Flip("characters/roxxy/char_roxxy_29.png", horizontal=True)
image roxxy 30f = im.Flip("characters/roxxy/char_roxxy_30.png", horizontal=True)
image roxxy 31f = im.Flip("characters/roxxy/char_roxxy_31.png", horizontal=True)
image roxxy 32f = im.Flip("characters/roxxy/char_roxxy_32.png", xoffset=67, horizontal=True)
image roxxy 33f = im.Flip("characters/roxxy/char_roxxy_33.png", xoffset=67, horizontal=True)
image roxxy 33bf = im.Flip("characters/roxxy/char_roxxy_33b.png", xoffset=33, horizontal=True)
image roxxy 59f = im.Flip("characters/roxxy/char_roxxy_59.png", horizontal=True)
image roxxy 66f = im.Flip("characters/roxxy/char_roxxy_66.png", xoffset=110, horizontal=True)
image roxxy 68bf = im.Flip("characters/roxxy/char_roxxy_68b.png", xoffset=20, horizontal=True)
image roxxy 68cf = im.Flip("characters/roxxy/char_roxxy_68c.png", xoffset=20, horizontal=True)
image roxxy 80f = im.Flip("characters/roxxy/char_roxxy_80.png", horizontal=True)
image roxxy 81f = im.Flip("characters/roxxy/char_roxxy_81.png", horizontal=True)
image roxxy 82f = im.Flip("characters/roxxy/char_roxxy_82.png", horizontal=True)
image roxxy 84f = im.Flip("characters/roxxy/char_roxxy_84.png", horizontal=True)
image roxxy 106f = im.Flip("characters/roxxy/char_roxxy_106.png", horizontal=True)
image roxxy 107f = im.Flip("characters/roxxy/char_roxxy_107.png", horizontal=True)
image roxxy 108f = im.Flip("characters/roxxy/char_roxxy_108.png", horizontal=True)

image roxxy_wet_undies_f = im.Flip("characters/roxxy/char_roxxy_wet_undies.png", xoffset=91, yoffset=-90, horizontal=True)
image roxxy_wet back_f = im.Flip("characters/roxxy/char_roxxy_wet_back.png",xoffset=-207,yoffset=-73, horizontal=True)
image roxxy_wet hurt_f = im.Flip("characters/roxxy/char_roxxy_wet_hurt.png",xoffset=92,yoffset=-296, horizontal=True)
image roxxy_wet_f = im.Flip("characters/roxxy/char_roxxy_wet.png",xoffset=0,yoffset=-360, horizontal=True)


image roxxy bikini 1f = im.Flip("characters/roxxy/char_roxxy_bikini_01.png", horizontal=True)
image roxxy bikini 2f = im.Flip("characters/roxxy/char_roxxy_bikini_02.png", horizontal=True)
image roxxy bikini 13f = im.Flip("characters/roxxy/char_roxxy_bikini_13.png", horizontal=True)
image roxxy bikini 14f = im.Flip("characters/roxxy/char_roxxy_bikini_14.png", horizontal=True)
image roxxy bikini 15f = im.Flip("characters/roxxy/char_roxxy_bikini_15.png", horizontal=True)
image roxxy bikini 17f = im.Flip("characters/roxxy/char_roxxy_bikini_17.png", horizontal=True)
image roxxy bikini 18f = im.Flip("characters/roxxy/char_roxxy_bikini_18.png", horizontal=True)
image roxxy bikini 19f = im.Flip("characters/roxxy/char_roxxy_bikini_19.png", horizontal=True)
image roxxy bikini 19bf = im.Flip("characters/roxxy/char_roxxy_bikini_19b.png", horizontal=True)
image roxxy bikini 20f = im.Flip("characters/roxxy/char_roxxy_bikini_20.png", horizontal=True)
image roxxy bikini 21f = im.Flip("characters/roxxy/char_roxxy_bikini_21.png",xoffset=33, horizontal=True)
image roxxy bikini 22f = im.Flip("characters/roxxy/char_roxxy_bikini_22.png",xoffset=33, horizontal=True)
image roxxy bikini 24f = im.Flip("characters/roxxy/char_roxxy_bikini_24.png",xoffset=33, horizontal=True)

image roxxy bikini usa 9f = im.Flip("characters/roxxy/char_roxxy_bikini_usa_09.png", horizontal=True)
image roxxy bikini usa 10f = im.Flip("characters/roxxy/char_roxxy_bikini_usa_10.png", horizontal=True)
image roxxy bikini usa 11f = im.Flip("characters/roxxy/char_roxxy_bikini_usa_11.png", horizontal=True)
image roxxy bikini usa 12f = im.Flip("characters/roxxy/char_roxxy_bikini_usa_12.png",xoffset=14, horizontal=True)
image roxxy bikini usa 13f = im.Flip("characters/roxxy/char_roxxy_bikini_usa_13.png",xoffset=14, horizontal=True)
image roxxy bikini usa 16f = im.Flip("characters/roxxy/char_roxxy_bikini_usa_16.png",xoffset=14, horizontal=True)
image roxxy bikini usa 17f = im.Flip("characters/roxxy/char_roxxy_bikini_usa_17.png",xoffset=14, horizontal=True)
image roxxy bikini usa 18f = im.Flip("characters/roxxy/char_roxxy_bikini_usa_18.png",xoffset=14, horizontal=True)

image roxxys_beach_sidef = im.Flip("characters/roxxy/char_roxxy_sex_foursome_side.png", horizontal=True)


image crystal 5f = im.Flip("characters/crystal/crystal_05.png", horizontal=True)
image crystal 6f = im.Flip("characters/crystal/crystal_06.png", horizontal=True)
image crystal 9f = im.Flip("characters/crystal/crystal_09.png", horizontal=True)
image crystal 10f = im.Flip("characters/crystal/crystal_10.png", horizontal=True)
image crystal 11f = im.Flip("characters/crystal/crystal_11.png", horizontal=True)


image xtra 36f = im.Flip("characters/xtra/char_xtra_36.png", horizontal=True)


image tyrone 1f = im.Flip("characters/tyrone/char_tyrone_01.png", horizontal=True)
image tyrone 2f = im.Flip("characters/tyrone/char_tyrone_02.png", horizontal=True)
image tyrone 3f = im.Flip("characters/tyrone/char_tyrone_03.png", horizontal=True)
image tyrone 6f = im.Flip("characters/tyrone/char_tyrone_06.png", horizontal=True)
image tyrone 7f = im.Flip("characters/tyrone/char_tyrone_07.png", horizontal=True)
image tyrone 8f = im.Flip("characters/tyrone/char_tyrone_08.png", horizontal=True)
image tyrone 9f = im.Flip("characters/tyrone/char_tyrone_09.png", horizontal=True)
image tyrone 10f = im.Flip("characters/tyrone/char_tyrone_10.png", horizontal=True)


image dewitt 1bf = im.Flip("characters/dewitt/char_dewitt_01b.png", horizontal=True)
image dewitt 3bf = im.Flip("characters/dewitt/char_dewitt_03b.png", horizontal=True)
image dewitt 6f = im.Flip("characters/dewitt/char_dewitt_06.png", horizontal=True)
image dewitt 9bf = im.Flip("characters/dewitt/char_dewitt_09b.png", horizontal=True)
image dewitt 9df = im.Flip("characters/dewitt/char_dewitt_09d.png", horizontal=True)
image dewitt 9ff = im.Flip("characters/dewitt/char_dewitt_09f.png", horizontal=True)
image dewitt 10bf = im.Flip("characters/dewitt/char_dewitt_10b.png", horizontal=True)
image dewitt 11bf = im.Flip("characters/dewitt/char_dewitt_11b.png", horizontal=True)
image dewitt 13f = im.Flip("characters/dewitt/char_dewitt_13.png", horizontal=True)
image dewitt 14f = im.Flip("characters/dewitt/char_dewitt_14.png", horizontal=True)
image dewitt 18f = im.Flip("characters/dewitt/char_dewitt_18.png", horizontal=True)
image dewitt 19f = im.Flip("characters/dewitt/char_dewitt_19.png", horizontal=True)
image dewitt 31f = im.Flip("characters/dewitt/char_dewitt_31.png", horizontal=True)
image dewitt 32f = im.Flip("characters/dewitt/char_dewitt_32.png", horizontal=True)
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
